tasks:
  - name: build and test
    init:
      pushd src/known-folders && git submodule init && git submodule update && popd
      && pushd src/zinput && git submodule init && git submodule update && popd